name: Build Windows EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        ls -R
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run PyInstaller
      run: |
        pyinstaller --onefile --windowed --name="EmailGenerator" --collect-all="PySide6" emailgenerator.py

    - name: Upload the EXE
      uses: actions/upload-artifact@v4
      with:
        name: Windows-EXE
        path: dist/EmailGenerator.exe
