name: Build Windows EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # This installs PySide6, PyInstaller, etc.
    
    # This single step replaces all the complex path-finding logic.
    - name: Install PyInstaller Hooks 
      run: pip install pyinstaller-hooks-contrib

    # The PyInstaller command is now very simple.
    - name: Run PyInstaller
      run: pyinstaller --onefile --windowed --name="EmailGenerator" emailgenerator.py

    - name: Upload the EXE
      uses: actions/upload-artifact@v4
      with:
        name: Windows-EXE
        path: dist/EmailGenerator.exe
